version: "3.7"

services:
  web:
    build: .
    container_name: web
    volumes:
      - .:/myapp
    command: rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    networks:
      - myapp
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - myapp

networks:
  myapp:
    external: true

volumes:
  mysql-data:
